name: GitHub Actions
on: [push]
permissions:
  id-token: write
  contents: read
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::494526681395:role/goudan-for-github-action
          aws-region: ap-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker pull nginx:1.23.2
          docker tag nginx:1.23.2 ${REGISTRY}/goudan-test:${GITHUB_RUN_ID}
          docker push ${REGISTRY}/goudan-test:${GITHUB_RUN_ID}

      - name: shell check
        id: hello-goudan
        uses: weijiany/shellcheck-action@0.1.0
        with:
          dir: '.'

      - name: Run demo script
        run:  ./demo.sh "${{ steps.hello-goudan.outputs.time }}"
  Job-2:
    runs-on: ubuntu-latest
    steps:
      - name: test concurrent
        run: echo hello world.
