name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: hello goudan
        uses: weijiany/hello-world-docker-action@0.1.0
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Run demo script
        run:  ./demo.sh
