name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::494526681395:role/goudan-for-github-action
          aws-region: ap-east-1

      - name: push to ECR
        run: ./auto/push.sh

      - name: shell check
        id: hello-goudan
        uses: weijiany/shellcheck-action@0.1.0
        with:
          dir: '.'

      - name: Run demo script
        run:  ./demo.sh "${{ steps.hello-goudan.outputs.time }}"
